/* Shared list of topic pages for cross-topic features (hot/must, global search). */
var NOTES_TOPICS = [
  { url: 'behavioral.html',     name: 'Behavioral' },
  { url: 'core-java.html',      name: 'Core Java' },
  { url: 'concurrency.html',    name: 'Concurrency' },
  { url: 'spring-core.html',    name: 'Spring Core' },
  { url: 'spring-boot.html',    name: 'Spring Boot' },
  { url: 'rest-security.html',  name: 'REST & Security' },
  { url: 'soap.html',           name: 'SOAP Web Services' },
  { url: 'sql.html',            name: 'SQL & RDBMS' },
  { url: 'plsql.html',          name: 'Oracle PL/SQL' },
  { url: 'mongodb.html',        name: 'MongoDB' },
  { url: 'elasticsearch.html',  name: 'Elasticsearch' },
  { url: 'microservices.html',  name: 'Microservices' },
  { url: 'messaging.html',      name: 'Messaging' },
  { url: 'system-design.html',  name: 'System Design' },
  { url: 'bfsi.html',           name: 'Core Banking & BFSI' },
  { url: 'sdlc.html',           name: 'SDLC & Agile' },
  { url: 'scenarios.html',      name: 'Scenario-Based' },
  { url: 'cloud.html',          name: 'Cloud (AWS / Azure)' },
  { url: 'docker-k8s.html',     name: 'Docker & Kubernetes' },
  { url: 'cicd.html',           name: 'CI/CD & Git' },
  { url: 'production.html',     name: 'Production Debugging' },
  { url: 'appserver.html',      name: 'WebLogic / Tomcat' },
  { url: 'testing.html',        name: 'JUnit & Testing' },
  { url: 'jmeter.html',         name: 'JMeter & Performance' },
  { url: 'unix.html',           name: 'Unix & Shell' },
  { url: 'frontend.html',       name: 'Frontend Basics' },
  { url: 'dsa.html',            name: 'DSA Interview Set' },
  { url: 'ai-llm.html',         name: 'AI / LLM' },
  { url: 'puzzles.html',        name: 'Code Puzzles' }
];
